development:
  adapter: postgresql
  database: mobiledelivery_development
  username: postgres
  password: ubuntu
  host: localhost
  encoding: UTF8


test:
  adapter: postgresql
  database: mobiledelivery_test
  username: postgres
  password: ubuntu
  host: localhost
  encoding: UTF8


production:
  adapter: postgresql
  database: mobiledelivery_production
  username: postgres
  password: ubuntu
  host: localhost
  encoding: UTF8
